#!/bin/bash

# Variablen für die Farben

black=$(echo -e '\e[30m')
red=$(echo -e '\e[31m')
green=$(echo -e '\e[32m')
brown=$(echo -e '\e[33m')
blue=$(echo -e '\e[34m')
purple=$(echo -e '\e[35m')
cyan=$(echo -e '\033[1m\e[36m')
yellow=$(echo -e '\e[1;33m')
white=$(echo -e '\e[1;37m')
dark_gray=$(echo -e '\e[1;30m')
light_red=$(echo -e '\e[1;31m')
light_green=$(echo -e '\e[1;32m')
light_blue=$(echo -e '\e[1;34m')
light_purple=$(echo -e '\e[1;35m')
light_cyan=$(echo -e '\e[1;36m')
light_gray=$(echo -e '\e[37m')
orange=$(echo -e '\e[38;5;202m')
light_orange=$(echo -e '\e[38;5;214m')
bold=$(echo -e '\033[1m')
reset=$(echo -e '\033(B\033[m')
unterstrich=$(echo -e '\033[4m')

if [[ $1 = -i ]]
then
    echo -e "Checking repositorys..."
    sleep 0.7
    sudo apt install $2
    sleep 0.2
    echo -e "Package ${2} was successfullied installed"

else
if [[ $1 = -r ]]
then
    echo -e "Removing package ${2}"
    sleep 0.7
    sudo apt remove $2
    sleep 0.2
    echo -e "Package ${2} was successfullied removed"

else
if [[ $1 = -u ]]
then
    echo -e "Checking for updates..."
    sleep 0.7
    sudo apt update
    sleep 0.2

else
if [[ $1 = -ug ]]
then
    echo -e "Checking for updates..."
    sleep 1
    sudo apt upgrade

else
if [[ $1 = -l ]]
then
    echo -e "Listing all packages... This may take a while..."
    sleep 0.5
    apt list

else
if [[ $1 = -ar ]]
then
    echo -e "Removing all unused packages now..."
    sleep 0.5
    sudo apt autoremove

else
if [[ $1 = -v ]]
then
    echo -e "EP-Version: 1.0.6 (Alpha)"

else
if [[ $1 = -remove-ep ]]
then
    sudo rm /usr/bin/ep

else
if [[ $1 = -info ]]
then
    echo -e "${light_cyan}Info about EasyPackage (SPM)${reset}"
    echo -e "********************************************************"
    sleep 0.01
    echo -e "Easy Package is a little script written in bash,"
    echo -e "which tries to make the usage of apt a little bit"
    echo -e "easier for you."
    echo -e "We know that some people might think this script"
    echo -e "is very useless, but we dont think so!"
    echo -e "If you dont like it you can just enter the command"
    echo -e "${light_blue}'ep -remove-ep'${reset} to remove it."

else
if [[ $1 = -h ]]
then
    echo -e "${light_green}Usage of EasyPackage${reset}"
    echo -e "********************************************************"
    sleep 0.01
    echo -e "ep -i <Package>: Installs a package"
    echo -e "ep -r <Package>: Removes a package"
    echo -e "ep -u: Searching for avaible Updates"
    echo -e "ep -ug: Upgrades Packages if there are avaible updates"
    echo -e "ep -l: Listing all avaible Packages"
    echo -e "ep -ar: Remove automatically all unused Packages"
    echo -e "ep -v: Display current version of Easy Package"
    echo -e "ep -info: Show more informations about Easy Package"
    echo -e ""
    echo -e "ep Version 1.0.4 (Alpha) for LinuxGuides OS"

else
    echo -e "\033[31mERROR:\033[0m Invalid option '${1}'"
    echo -e "Use ep -h for more Informations"
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
